### ISSUE TITLE
[epic] Design and Roadmap for v1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#10]
High level design / architecture plus technical roadmap for DataHub Next

## Acceptance

- [ ] Spec out example source repos / content
- [ ] Spec out domain model
- [ ] Spec out initial architecture

**Comment by rufuspollock** [comment]
Making good progress on an initial plan. Have a goal for v1.

**Comment by rufuspollock** [comment]
Just updated the roadmap for v1 #1 from results of discussions of last 10d. Making good progress. What remains is probably to spec out developments by workstream and identify a "v1" or stages to that.
