### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by luccasmmg** [datopian/datahub-next#107]
We want a way for the users to subscribe to plans

## Job Stories

When I sign up to Datahub i want to be able to subscribe to a plan and have access to its features

## Acceptance

- [ ] Have a way to quickly setup plans and make them available
- [ ] Have a way to view what plan the user is currently using
- [ ] Users must be able to cancel plans and choose others
- [ ] User must be able to use most credit cards and payment options
- [ ] Have a page displaying the subscription options

## Tasks

- [ ] Create stripe account/project(Currently on my personal account)
- [ ] Modify the Supabase DB to store payment information
- [ ] Add a biling page with the overview of the plans
- [ ] Make the subscription possible
- [ ] Show what plan the user is currently subscribed to in the dashboard
- [ ] Have a cancel plan button that allows the user to cancel its subscription
- [ ] Added information about env variables in README

**Comment by luccasmmg** [comment]
@rufuspollock is this more or less what you wanted with the subscriptions/billing?

https://user-images.githubusercontent.com/11317382/230110368-aafcf143-cf9f-401c-916e-afe3a482e777.mp4
