### ISSUE TITLE
Project create and update API v0.1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#11]
When creating projects i want an API so that i can create projects directly from a github url or from full project object 

TODO: document project object.

## Acceptance

- [x] Function that given a github repo e.g. https://github.com/datasets/finance-vix returns a Project object 💋 **✅2023-03-30 in #79 and #76**
- [x] Function that indexes project object into typesense 💋 **✅ 2023-04-04 FIXED. The Project class now has an `index()` method. See linked PR**
- [x] Have a project API `/api/project` **✅ 2023-04-04 FIXED. Not looking great since it doesn't seem to be using a good API design, but :kiss: for now**
- [x] Create/update a project `/api/project POST` **✅ 2023-04-04 FIXED. POSTs to `/api/project` will upsert a serialized project document on Typesense based on the request body `{ owner: ..., name: ... }`**
  - [ ] Can create from github repo url alone **:negative_squared_cross_mark: 2023-04-04 we are not really using a URL, but owner and name**
  - [x] Note can post update without project id and that gets looked up for you from name/owner and added automatically (if name has changed, it would create a new entry instead of updating old one which is ok...) **✅ 2023-04-04 FIXED. The implementation is not exactly this, but you don't have to provide a project id to update an index, just owner and name**
- [x] Docs for this at /docs/ **✅ FIXED. Created an API document on /notes (I guess docs was what we were using at that time), see https://datahub.io/notes/api**
- [x] [Optional] GET a project (uses search in background) `/api/project GET` **✅ 2023-04-04 FIXED. GETs to `api/project` will return a Project based on the owner and name query params `/api/project?owner=...&name=...`, although instead of search we are using retrieve**

Bonus:

- [ ] Have a script we can run to index github urls 💋 **:negative_squared_cross_mark: 2023-04-04 not doing this because our project lib file is a TS file and it also depends on next/getConfig, so it would not be a matter of just importing the project lib file in the script and calling some functions. What we could do is create a script to send a request to the API, but that would be just a wrapper for a curl command and would require the project to be running**

NB: no authorization at the present.

## Tasks

In lib ...

- [x] Create library function to construct project object given github url 💋 
  - [x] Create test
  - [x] select libraries (probably use official [octokit.js](https://github.com/octokit/octokit.js) though can also just use apollo and graphql e.g. https://github.com/datopian/data-literate/blob/main/lib/github.js)
  - [x] Write code and pass test
- [x] Add function to index to typesense (converts from Project to typesense format and indexes) 💋 
  - [x] test
  - [x] code
- [x] API function
  - [x] Create test (jest / playwright)
  - [x] Pass test

## Notes

Algorithm can be broken down at three levels from most convenient: 

- Index: given github repo url
  - look up github repo metadata
  - get info from repo e.g. datapackage.json and README.md
  - consolidate on a title: use datapackage.json title if present and non-empty, use github repo description, otherwise just use name title-ified
  - add an id (randomly generated, TODO: check unique by name and owner)
- Index: given an object already in right form for schema e.g. like

  ```
  {
    id: 
    name:
    title:
    owner:
    github_repo:
    readme:
    datapackage:
  }
  ```

Existing action: https://github.com/datopian/datahub-gh-actions/blob/main/index-datapackage/action.yml

**Comment by demenech** [comment]
@rufuspollock can I create a new cluster on TypSense Cloud for this? See https://cloud.typesense.org/clusters

**Comment by demenech** [comment]
## Updates 2023-04-04

PR: https://github.com/datopian/datahub-next/pull/103

### Changes

- Created a Typesense cluster for Datahub Next, see https://cloud.typesense.org/clusters/hd69tx1nf2yjvrqwp 
- Created `lib/typesenseClient.ts` (copied the code from git-dms)
- `lib/project.ts`
  - Renamed the `ProjectProps` interface to `SerializedProject`, based on the pattern used on the latest refactoring of MarkdownDB
  - Added an id field to the Project class, it's calculated using the `github_repo` field (sha1 -> hex), needed so that we can upsert documents on Typesense
    - In the future we might want to rethink this, probably won't work when a repo is renamed 
  - `getProjectFromGitHub` moved to a static method in Project, so that we can use it as `Project.getFromGitHub(owner, name)
  - New methods:
    - `project.index()` -  Indexes the serialized project on Typesense
    - `project.deindex()` - Deindexes the project on Typesense, created mainly for tests clean up but certainly useful for other purposes
    - `project.retrieve()` - Retrieves the index of a project from Typesense, used on the next method...
    - `project.initFromIndex()` and `static Project.getFromIndex()` - similar to how we populate a Project object by requesting information from GitHub with `getFromGitHub()`, `getFromIndex()` will populate the Project with data coming from Typesense. 
- `pages/api/project,ts`
  - If POST, will upsert a project document on Typesense based on the request body (e.g `{ owner: "datahubio", name: "test-data-repo-1" }`) 
  - If GET, will retrieve a document from Typesense based on the request query params (e.g `/api/project?owner=datahubio&name=test-data-repo-1`)
  - Probably a bad API design, but :kiss: for now
- Created an e2e test for the API and a unit test for the lib
  - Updated the test actions on GitHub to set up the typesense related env vars
  - On the unit test action we are using a matrix to execute the tests using two different versions of node, to make the unit tests work properly I had to ensure these "two unit test actions"  were not being executed in parallel

**Comment by demenech** [comment]
FIXED. See commit https://github.com/datopian/datahub-next/commit/3951ecaa2947e08d8761af2a3a82cd9474246647 and docs https://datahub.io/notes/api
