### ISSUE TITLE
[v0.1] Clean up old left-over code especially data literate stuff

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#14]
There is some code that has become unused with the Flowershow upgrade in Jan 2023 but was not removed (just moved aside into `components/custom`. this includes old data literate work from Feb/March 2022.

Let's remove this so we can start again clean.

## Acceptance

- [x] No unused components **✅2023-03-01 removed all of custom/components plus lib/utils.js**
- [x] No old data literate content (if not working/used) **✅2023-03-01 components in `components/custom plus content/data-literate-demo.md**

## Tasks

- [x] Remove old data literate code from the codebase  **✅ 2023-02-28 clean-up PR: https://github.com/datopian/datahub-next/pull/13**
  - [x] What is the old data literate code? **✅ 2023-02-28 Files from an old integration that's not working currently. Specifically `content/data-literate-demo.md` and `components/custom/` items specifically `DataLiterate.jsx`, `LineChart.jsx`, `Excel.jsx`, `Table.jsx`, `TableGrid.jsx`** 
  - [x] Where is it used? (ie. what content pages use it, if any? **✅  2023-02-28  Only in a demo content file `content/data-literate-demo.md` that's excluded from the build.** 
  - [x] Make sure it will not impact any page **✅  2023-02-28 no other components were affected.** 
  - [x] Remove the code
- [x] What other code can be clean up?
    - [x] could also remove other components in `component/custom` e.g. `Footer.jsx`, `Nav.jsx`, `Banner.jsx`, `Layout.jsx` `BlogPost.jsx` as all unused
    - [x] `lib/utils.js` (unused)

### What is the old data literate code?

The `data-literate` components can be found in this project due to an earlier integration of data-literate content in 2022. This was finished but then moved aside probably during the remake of Datahub.io using Flowershow. In the PR that added it (https://github.com/datopian/next.datahub.io/pull/47), there's a note about this:

> Excluding data-literate-demo for now as it uses lots of custom components and currently causes build to fail
  
The code was kept as a WIP, and the only md file that was making use of the components was excluded on contentlayer config (see commit: 

https://github.com/datopian/next.datahub.io/pull/47/commits/8f8499fbd717736b97e3e09afc1b73fc560f2173#diff-99dbb8af0b5bc858dda68b21ed845433d9153fd9bfef58348e40ad32ed7adaefR11):

```javascript
contentExclude: ["data-literate-demo.md"],
```

### Where is it used? (ie. what content pages use it, if any?)

The only content page that's using it is `content/data-literate-demo.md`, which is a copy of the data-literate demo and which is not accessible at all.

**Comment by rufuspollock** [comment]
FIXED. All done.
