### ISSUE TITLE
v0.1: implement DRD graph components

### ISSUE THREAD

**Issue by demenech** [datopian/datahub-next#17]
Implement the graph components that are supported by `data-literate`.

Part of #3 

## Acceptance criteria

- [x] Which are the old graph components? **✅2023-03-02 Vega, Vega Lite, Line Chart based on Plotly (?)**
- [x] Which do we want to use? **✅2023-03-02 if easy, let's do all of them but prioritize vega and vega-lite to start with**
- [x] Graph components are implemented **✅ 2023-03-02 components were migrated from portal.js, PR: https://github.com/datopian/datahub-next/pull/23**
- [x] I can check out the new components on the demo mdx file **✅ 2023-03-10 ~components were added, but they are not working on prod. See notes below.~ Working. See https://datahub-next.vercel.app/tools/view**

## Tasks

- [x] Check the old examples and list the graph components 
- [x] Implement the graph components 
- [x] Add examples of usage of the graph components to our demo mdx file

### Issue on production

Currently, the graphs are working perfectly when on dev:
![image](https://user-images.githubusercontent.com/16550934/223100088-be9d14f9-f008-47d3-92fb-737bd79badbe.png)

But on production, the charts are not being displayed, although the controls for the chart do work:
![ss-2023-03-06-08:40:26](https://user-images.githubusercontent.com/16550934/223100586-f71bac5d-d0b3-47ac-be43-ee3b2e3a9f90.png)

And there are some errors on the console:
![ss-2023-03-06-08:41:35](https://user-images.githubusercontent.com/16550934/223100741-591fd4fc-3ff2-48f8-bc19-8f1ddf3541e5.png)

**Comment by rufuspollock** [comment]
@demenech has added notes about error to issue description.

**Comment by rufuspollock** [comment]
@demenech i assume this is still not working (after e.g. typescript upgrade etc)?

**Comment by demenech** [comment]
@rufuspollock it's working now https://datahub-next.vercel.app/tools/view
 
I will close the issue

**Comment by demenech** [comment]
FIXED. See https://datahub-next.vercel.app/tools/view and commit https://github.com/datopian/datahub-next/commit/fa2cb06640234b2af46e03f48c6d95cd6777c74a.
