### ISSUE TITLE
Project showcase v0.1: render the README for a github repo using data rich doc pipeline

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#21]
Display "showcase" page (base page) for a (data) project. Direct proxy approach where we proxy connect over (nothing cached in our own db).

Assuming the data project "owner/name" correspond directly to github naming and github repo is public (so can access raw.github urls for now)

🚩 This would only work on the Vercel branch

## Acceptance

- [x] `datahub.io/@{owner}/{project}` renders the README in github repo `{owner}/{project}` for public repos **✅ 2023-03-17 done. Included in the PR. See https://datahub-next-2d10zsmro-datopian1.vercel.app/@datahubio/test-data-repo-1**
- [x] We have a test by eye (or better e2e) for this  **✅ 2023-03-17 added a very basic E2E test**
  - [x] we have a test/demo repo eg. github.com/datopian/datahub-test-repo-1  **✅ 2023-03-17 See https://github.com/datahubio/test-data-repo-1**

## Tasks

- [x] Write test for playwright
  - [x] create demo/test repo
- [x] Create route for `/@{owner}/{project}`
- [x] Library function Loads content from github repo README.md (uses raw urls rather than API for now)
- [x] Run through our render pipeline and render for data rich documents

___

PR: https://github.com/datopian/datahub-next/pull/62

**Comment by demenech** [comment]
@rufuspollock https://github.com/datopian/datahub-next/issues/51 took me longer than expected to conclude, so I'll have to deliver this one tomorrow

**Comment by demenech** [comment]
Issue: https://github.com/datopian/datahub-next/issues/21

## Changes:

- Added `pages/@org/[org]/[project]` and added a rewrite rule from `"/@:org/:project"` to `"/@org/:org/:project"`
    - Without the rewrite rule, `/segment1/segment2` would always redirect to the project showcase page, and paths like `docs/dms` would not work  
- Added `lib/organization.ts`, which just wraps some Octokit methods. Very simple for now.
- Added a very very basic E2E test. It just tests if the page has the correct title and if it's rendering https://github.com/datahubio/test-data-repo-1 properly

## Notes

### API limits

An important note is that there are some usage limits for the Github Rest API: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts . Limits for unauthenticated users seem to be kinda low, so we might have issues if there are too many requests in one hour.

___

PR: https://github.com/datopian/datahub-next/pull/62

___

@rufuspollock is a very simple E2E test ok? I'm not sure how to handle this.

**Comment by rufuspollock** [comment]
FIXED. Working, see https://datahub-next-2d10zsmro-datopian1.vercel.app/@datahubio/test-data-repo-1
