### ISSUE TITLE
Markdown rendering pipeline v0.1: feature parity to Flowershow on text 

### ISSUE THREAD

**Issue by demenech** [datopian/datahub-next#27]
We want to replace/upgrade the Flowershow render pipeline so that:

- we can load markdown content not on disk e.g. from github repo (see #15 for more on why next-mdx-remote)
- we don't depend on node runtime or access to disk (so that we can run on e.g. edge runtime)
- we have a cleaner API for testing (atm w/ contentlayer we can't really test the render pipeline)
- we are ready for componentizing and enhacing the pipeline going forward (e.g. splitting parse and transformation) and replacing content layer (e.g. type checking) 
- we are ready for integration with our "content base"

Further context on point 1 + 2: To make it work on the deployment (Cloudflare), we have to change our Next.js runtime to `experimental-edge` and get rid of our dependency on Node.js native API, so that SSR and the API folder work. See more notes about this on https://github.com/datopian/datahub-next/issues/4.

## 🚧 Status

WIP but we're successful rendering external md pages at `/tools/view?url` path with support for the plugins listed below.

Deploy preview: https://datahub-next-1lkuznexd-datopian1.vercel.app

Preview of [this fixture md page](https://github.com/datopian/datahub-next/blob/27-rendering-pipeline/__tests__/e2e/fixtures/markdown.md) rendered: https://datahub-next-1lkuznexd-datopian1.vercel.app/tools/view?url=https://raw.githubusercontent.com/datopian/datahub-next/27-rendering-pipeline/__tests__/e2e/fixtures/markdown.md 

PR draft for reference: https://github.com/datopian/datahub-next/pull/38/files

## Acceptance

- [x] Support all the major markdown features we currently support (or document if major blockers)
  - [x] mermaid
  - [x] wiki links **quick & dirty solution: temporarily replaced our remark plugin with original `remark-wiki-link` package and combined it with a custom resolver of wiki link permalinks to relative urls with new/target `url` query param**
  - [x] callouts
  - [x] math **temporarily replaced with `rehype-katex` as it reportedly covers most of latex**
  - [x] gfm
  - [x] inline table of contents
  - [x] yt embeds
  - [x] smartypants
  - [x] autolink headings **works but requires styles fixes**
  - [x] code lines numbers & highlighting
- [x] Not have filesystem dependencies (or again clearly documented for future so we can try to resolve)
- [x] Not dependent on node runtime so we can run on edge (ditto) **✅2023-03-10 ❌ wontfix - this is quite painful - see notes below and soon in a notes file**
- [x] Supports data rich documents
  - [ ] clearly documented set of React components that are available for use in MDX 

Extras

- [ ] How to handle layouts (if we want them)
- [ ] How we will handle getters etc

Bonus results:

- [x] Can change Next.js runtime to `experimental-edge` (which address #4) **✅2023-03-13 ❌ wontfix for now - after discussion seems painful**

## Tasks

- [ ] Get a failing test!

### Progress

1. Enabled `experimental-edge` runtime in `tools/view.js` page and replaced `getStaticProps` with `serverSideProps`

2. For now I've commented out:
- `@flowershow/remark-wiki-link` - direct reference to `fs`
- `mdx-mermaid` - dependency reference to `fs`
- `rehype-prism-plus` - dependency reference to `document`
- `@flowershow/remark-callouts` - dependency reference to `document`

**Context:**

`chownr` has references to `fs` and is being used by:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/52197250/223559354-0a421c4c-9190-44ab-8d8f-bb94ee0d2ebe.png">

`micromark-core-commonmark` has references to `document` and is being used by:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/52197250/223559402-ba407086-44e5-4373-b598-3daff6b1466a.png">

`decode-named-characted-reference` has references to `document` and is being used by:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/52197250/223559473-b30c3e02-1152-4d35-89a9-228adaf171e2.png">

3. After commenting out the above packages there was still one that was using `decode-named-character-reference` in one of it's dependencies: `next-mdx-remote` itself (not listed above, because `npm list` only lists direct dependencies of the project).

4. Just to test if this is the only issue left, I've commented out the code using this package as well, so I tried to render a simple page (a div with some text) with `edge-runtime` config enabled. But then I got this internal server error:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/52197250/223559520-27fc4513-4015-47b8-bba6-87e3ad7ef5b0.png">

Which doesn't show up only when I switch back to the default `node` environment. 

5. I suspected this is an issue with Next.js version or version of some other dependency, so I tested a simple page with `edge-runtime` on our Flowershow website => **worked** (but had to temporarily remove custom `_app` as it is using Node API, more details below).

6. Upgraded Flowershow template used in this project (#33 PR tbd) and tested a simple edge page again => **works** (again, temporarily had to remove custom `_app` due to its dependencies on Node API)

**Currently: finishing clean up after upgarde and preparing a PR**
**Next: investigate why `next-mdx-remote` doesn't work with edge-runtime. If it's a relatively small thing that we don't need, we could probably fork and adjust the package (or submit a PR in `next-mdx-remote` that would decouple it from the core part) so that we can use it on edge without errors.**

### Potential issues with edge runtime

1. `next-mdx-remote` seems to have references to Node API:

![image](https://user-images.githubusercontent.com/52197250/223669085-a69531ee-9191-47de-a731-d2e6b15f905f.png)

### Potential refactoring needed code parts

1. Some parts of custom `_app` are using Node API as well (`@flowershow/core`?)

<img width="731" alt="image" src="https://user-images.githubusercontent.com/52197250/223708787-57adee60-ec52-406c-9a2c-e1871803e736.png">

**Comment by rufuspollock** [comment]
@olayway reading the issues you are having:

- i'd focus first on a unit test and ignore the edge runtime stuff
- once that is clearly passing against some fixture data then we can move on to edge stuff
- re edge stuff: maybe a clean nextjs install may be easiest - ie. start with clean install and add stuff e.g. `lib/markdown.mjs`

Finally, things like `puppeteer` for mermaid are marked as optional dependencies in the `package.json` for mdx-mermaid. I wonder if there is a way to exclude them from the install.

**Comment by olayway** [comment]
@rufuspollock I've quickly tested if using `lib/markdown` on Flowershow will work, and it seems that `next-mdx-remote` is using Node API as well. But I haven't investigated it thoroughly yet. See last part of the notes in the description.

**Comment by demenech** [comment]
hey @olayway , great work. About the last error, try deleting the custom _document in the project. I think that's what worked for me, but then I got stuck on finding a workaround for the `next-mdx-remote` issue.

**Comment by olayway** [comment]
@demenech I didn't need to remove `_document` but rather `_app`, but it is due to a different error (I'll add it in the description as well). This one however is related strictly to `next-mdx-remote`.

**Comment by olayway** [comment]
@rufuspollock I've upgraded Flowershow and I've managed to run the app with a simple page that uses edge environment. I'll create a PR with the upgrade and will continue investigating if `next-mdx-remote` is even able to run on the edge.

**Comment by rufuspollock** [comment]
> will continue investigating if next-mdx-remote is even able to run on the edge, cuz I guess there is no point in trying to work on the pipeline that uses it if we won't be able to make it work. Am I right?

Hmm, we need to distinguish two parts here:

- Pulling content and doing render server side which requires no deps on reading from disk to render
- Running in edge mode (needed for cloudflare)

We definitely need item (1) but (2) could be dropped if we dropped cloudflare.

So strictly, yes we still want this new pipeline even if we don't use edge. ... and so strictly your guess is incorrect there ...

**Comment by olayway** [comment]
@rufuspollock I wasn't suggesting we don't need a pipline

> cuz I guess there is no point in trying to work on the pipeline **that uses it** [`next-mdx-remote`] if we won't be able to make it work

And if we don't care about running it all on edge why do we think there is any need to worry about all these packages that use Node API?

**Comment by rufuspollock** [comment]
> And if we don't care about running it all on edge why do we even spend time trying to remove dependencies on Node API?

I think 2 things have got confused here in the discussion:

- Removing dependencies on file system calls (e.g. in remark-wiki-link-plus)
- Removing dependencies on node runtime (needed for edge stuff)

Former we definitely need. Latter is (initially at least) a nice to have.

**Comment by demenech** [comment]
FIXED. See commit https://github.com/datopian/datahub-next/commit/6e74831c0a9135d9a2cc5816e473b0b6dea496a8 and example https://datahub-next.pages.dev/test/markdown
