### ISSUE TITLE
[epic] v0.1: cloud-based rendering of data-rich document (MDX+D) into a web page

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#3]
Cloud-based rendering of data-rich document (MDX+D) with inline data into a web page

## Sprint goals

- rendering a data-rich markdown with a table given its url
  - Markdown rendering pipeline with SSR: take what we have in Flowershow and run over a single input markdown file
  - Table based on react-table

Stretch

- passing a github repo url with a README.md *and* a csv and the README references the CSV and it "just" works!
  - e.g. `/tools/view?github_url=https://github.com/datopian/datahub-next-test-1/`
  - What does this require?
- graphs ... (can start with vega or vega-lite i think)

## Example input markdown file

(TODO: this may not be exactly accurate ...)

```mdx
# Hello World

Here is my data table

<DataTable data=[
  { "a": 1, "b": 2}
  ]
  />
```

## Acceptance

- [ ] `next.datahub.io/tools/view?url=path-to-markdown-file` displays a preview
- [ ] Data-rich features
  - [x] Shows a table for inline data
  - [ ] BONUS: supports graphs (as per old examples)
  - [ ] Notes on "bad smells" or ways we could/should improve or refactor
- [x] Supports most of the features that flowershow does in terms of markdown processing (mainly a job of adding remark plugins)
  - [x] What features are those? **✅2023-03-03 Remark and Rehype plugins: Git Flavored Markdown, Table of Contents in the sidebar, math (not working properly rn), smartypants, callouts, video embedding, wikilink, mermaid (not working properly rn), prims code highlighting, auto link headings, slug (add ids to headings)**

Bonus

- [ ] (?) `next.datahub.io/tools/view?github_repo=url` displays a preview of README.md (for public github repos)

## Tasks

- [x] (?) remove use of contentlayer **✅2023-02-27 ❌ wontfix for now. actually probably leave for now as useful for docs etc**
- [x] have a core render function given a md/mdx file
  - [x] Review previous work in https://github.com/datopian/data-literate and https://github.com/datopian/portal.js/tree/main/site (later version of data-literate - may be a few improvements?) - rendered result at https://portaljs.org/data-literate/demo **✅ 2023-02-27 copied some code over. it is using next-mdx-remote**
  - [x] #15 **✅2023-03-01 for now we have good enough sense of going with next-mdx-remote and can revisit**
  - [x] Implement **✅ 2023-02-28 started on this with our port of data literate stuff using next-mdx-remote**
  - [x] Add Flowershow type stuff if needed e.g. remark plugins **✅ Added plugins that are used on Flowershow. Remark: GFM, TOC, Math (not working on Next.js because it causes a hydration problem, see https://github.com/remarkjs/remark-math/issues/80), Smartypants, Callouts, Embed, Wikilink, Mermaid (not working for now). Rehype: Prism plus, Auto link headings. Slug, Mathjax (disabled for now because remark-math is not working). PR: https://github.com/datopian/datahub-next/pull/18**

API Route

- [x] render MDX+D e.g. at  a route like `/tools/view?url=...` **:no_entry_sign:  2023-03-01 PR: https://github.com/datopian/datahub-next/pull/19/files . PR can't be merged because it can't be deployed to Cloudflare. See notes in https://github.com/datopian/datahub-next/issues/4**

Add data components

- [x] #5 **:heavy_check_mark: 2023-02-27 PR: https://github.com/datopian/datahub-next/pull/6** 
- [x] #17

Misc

- [x] #14 **✅2023-03-01 all removed ...**

### Docs and announce

- Tutorial: Getting started with DataHub (note we already have e.g. https://datahub.io/blog/we-have-some-important-updates-re-datahub from https://github.com/datopian/next.datahub.io/issues/30)
- Tutorial: Example of what DataHub can do? e.g. LHS: your README and RHS: the result

**Comment by demenech** [comment]
Only now I realized we already had part of the data-literate code migrated, see https://github.com/datopian/next.datahub.io/pull/47/commits/8f8499fbd717736b97e3e09afc1b73fc560f2173#diff-99dbb8af0b5bc858dda68b21ed845433d9153fd9bfef58348e40ad32ed7adaef
Here's the main file in our repo: https://github.com/datopian/datahub-next/blob/main/components/custom/DataLiterate.jsx

  
Maybe we can remove the files from the old implementation?

**Comment by demenech** [comment]
# RE: Decide on best mdx processor
We are currently using `next-mdx-remote`, because that's what was used for `data-literate`.

According to the `mdx-bundler` FAQ, the main difference between `mdx-bundler` and `next-ndx-remote` is that `mdx-bundler` supports syntax like `import Demo from './demo'` inside the mdx files (used by [contentlayer](https://github.com/contentlayerdev/contentlayer/blob/main/packages/%40contentlayer/core/package.json#L33)). In the `next-mdx-remote` README it's also mentioned:
> Since this project was initially created, Kent C Dodds has made a similar project, [mdx-bundler](https://github.com/kentcdodds/mdx-bundler). This library supports imports and exports within a mdx file (as long as you manually read each imported file and pass its contents) and automatically processes frontmatter. If you have a lot of files that all import and use different components, you may benefit from using mdx-bundler, as next-mdx-remote currently only allows components to be imported and made available across all pages. It's important to note that this functionality comes with a cost though - mdx-bundler's output is at least 400% larger than the output from next-mdx-remote for basic markdown content.

IMO, we could stick to `next-mdx-remote` for now, since this main difference doesn't seem advantageous for our purpose.

**Comment by rufuspollock** [comment]
> According to the mdx-bundler FAQ, the main difference between mdx-bundler and next-mdx-remote is that mdx-bundler supports syntax like import Demo from './demo' inside the mdx files (used by [contentlayer](https://github.com/contentlayerdev/contentlayer/blob/main/packages/%40contentlayer/core/package.json?rgh-link-date=2023-02-27T20%3A48%3A04Z#L33)). In the next-mdx-remote README it's also mentioned:

In fact, more than that. For our purposes we don't want or need that functionality (the files we are importing shouldn't import other files since we are server rendering ...)

**Comment by rufuspollock** [comment]
> Only now I realized we already had part of the data-literate code migrated, see https://github.com/datopian/next.datahub.io/commit/8f8499fbd717736b97e3e09afc1b73fc560f2173#diff-99dbb8af0b5bc858dda68b21ed845433d9153fd9bfef58348e40ad32ed7adaef
Here's the main file in our repo: [main/components/custom/DataLiterate.jsx](https://github.com/datopian/datahub-next/blob/main/components/custom/DataLiterate.jsx?rgh-link-date=2023-02-27T19%3A57%3A38Z)
>
> Maybe we can remove the files from the old implementation?

Please can add items for this in the issue description. I imagine we should check where that stuff is currently being used (if anywhere).

**Comment by demenech** [comment]
**Updates:** clean-up is done and merged (notes added), working on the MDX processor analysis
**Next 24h:** finish the analysis and work on graph components

**Comment by demenech** [comment]
**Updates:** `/tools/view?url=...` is working locally, but it can't be deployed because our deployment doesn't support getServerSideProps right now. Added remark and rehype plygins, see the notes on the ticket description.

**Comment by rufuspollock** [comment]
FIXED. See acceptance. all working. 🎉
