### ISSUE TITLE
[epic] MarkdownDB v0.1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#31]
Spike solution of an index of our markdown files so that I can quickly access the metadata and content I want.

See parent epic for details: #46

## Acceptance

- [x] We have a new `lib/markdowndb.js`
  - [x] We can index a folder of markdown files into sqlite3
  - [x] Query function to get all files
  - [x] Query to get files from folder e.g. all blog posts **✅ 2023-03-08 PR: https://github.com/datopian/datahub-next/pull/39**
  - [x] Index non markdown assets e.g. images, csv ... so can query for all images using same kind of options for markdown files e.g. by folder etc  **✅ 2023-03-08 PR: https://github.com/datopian/datahub-next/pull/39, added querying by filetype**
- [x] We are in a position to replace contentlayer.dev queries points with our new system (though doing this is separate issue - see #32) **✅ 2023-03-11 MarkdownDB is capable of indexing a folder and retrieving files using the Query function (which replaces the conentlayer.dev getters), we should be able to pipe that into next-mdx-remote and replace contenrlayer.dev**
- [x] Tests **✅ 2023-03-11 added unit test for indexing and querying**

## Tasks

- [x] Define basic schema **✅2023-03-07 see below**
- [x] Write a test and create a fixture folder of files **✅ 2023-03-08 PR: https://github.com/datopian/datahub-next/pull/36**
- [x] Walk content folder **✅ 2023-03-08 PR: https://github.com/datopian/datahub-next/pull/36**
  - For each markdown file extract frontmatter etc **✅ 2023-03-08 PR: https://github.com/datopian/datahub-next/pull/36**
- [ ] ...

### API sketch

Minimal viable API

`lib/db.ts`

```typescript
indexFolder(folderPath, sqliteDb)

interface Database {

  getFileInfo()

  getTags
  
  query(query: DatabaseQuery)
}

interface File {
  filetype
}

interface MarkdownFile extends File {
  frontmatter: // raw frontmatter
  // metadata // someday or even we just have specific objects that 
}
```

### What's the db schema?

```sql=

CREATE TABLE files (
  "_id": hashlib.sha1(path.encode("utf8")).hexdigest(),
  "_path": path,
  "frontmatter": json version of frontmatter
  "filetype": "markdown" | "csv" | "png" | ... (by extension?)
  -- "fileclass": "text" | "image" | "data"
  "type": type field in frontmatter if it exists -- ? do we want this
)
```

**Comment by rufuspollock** [comment]
@demenech want to acknowledge this exceptional quality comment. Also very clean PR.

**Comment by demenech** [comment]
## Update 2023-03-09

### PR to include initial tags and querying support

PR: https://github.com/datopian/datahub-next/pull/39

#### Changes:

- New tags and file_tags tables
- Query function implemented
  - Currently supports querying all, querying by folder and querying by tags 
- Get tags implemented
- New test cases
  - Expect tags table to exist
  - Expect file_tags table to exist
  - Check if all files were indexed using `Database.query()`
  - Check if we can query files by folder using `Database.query({ folder: "blog" })`
  - Check if we can query files by tag using `Database.query({ tags: ["economy"] })` 
- Left lots of comments of things to improve in the future


___

TODO: update ticket description tomorrow

**Comment by demenech** [comment]
Waiting for this PR https://github.com/datopian/datahub-next/pull/39 to be reviewed before closing

**Comment by rufuspollock** [comment]
FIXED. All done.

Note I've heavily refactored the issue description to move most of the generic content into a new top-level epic #46.

I've also copied the major open questions re types and frontmatter from @demenech comments up into the epic description.
