### ISSUE TITLE
[epic] Move off contentlayer.dev & upgrade or remove Flowershow stuff

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#32]
Currently we are using Flowershow which in turn uses contentlayer.dev. for processing local markdown content for docs, notes and blog 

We want to move off contentlayer.dev and upgrade/replace Flowershow (todo: clarify what parts).

Why? As discussed in #27 we want to replace/upgrade the Flowershow render pipeline so that:

- we can load markdown content not on disk e.g. from github repo (see #15 for more on why next-mdx-remote)
- we don't depend on node runtime or access to disk (so that we can run on e.g. edge runtime)
- we have a cleaner API for testing (atm w/ contentlayer we can't really test the render pipeline)
- we are ready for componentizing and enhacing the pipeline going forward (e.g. splitting parse and transformation) and replacing content layer (e.g. type checking) 
- Integrate a richer "ContentBase" so that ... 

## Acceptance

- [ ] contentlayer.dev code is no longer used
- [ ] all local pages rendering well

Bonus

- [ ] Can render remote content (statically)

## Tasks

- [x] #27 
- [x] #31 
- [x] Upgrade / replace Flowershow
  - [x] #33
  - [x] #51
  - [x] Assess what we can and would want to replace of old Flowershow (note we are happy to keep Flowershow! And may backport our improvements to Flowershow)
    - Layouts 
    - Mermaid is currently being imported from `@flowershow/core`
    - `siteConfig.ts` is getting the defaults from  `@flowershow/core`
    - remarkCallouts and remarkEmbed
    - BlogsList component

Extras

- [x] content/Excalidraw mdx files are not being parsed right now, we have to fix that or find a workaround **✅2023-03-17 ❌ these should not be parsed in any case so good not being parsed. these are only for obsidian/excalidraw. For site what we just need is svg - which we have by symlinking excalidraw folder into public**
- [x] Move `content/getters` into `getStaticProps` or `lib` (unless we are actually using still in markdown) **✅ 2023-03-17 PR: https://github.com/datopian/datahub-next/pull/63**

**Comment by demenech** [comment]
Getters removed. PR: https://github.com/datopian/datahub-next/pull/63

@rufuspollock I will replicate that to `with-SSR` after merged.

**Comment by rufuspollock** [comment]
FIXED.
