### ISSUE TITLE
[shape] Plan April 2024 ship iteration

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#325]
## Acceptance

- [x] Prioritized ideas list **✅2024-04-09 in #246**
- [x] New epic for april ship cycle **✅2024-04-09 #330**
- [ ] Items selected for shaping
- [ ] Items selected for shipping

## Tasks

```[tasklist]
### Get a plan
- [x] Review all inboxes and consolidate **✅2024-04-09 yesterday and today**
- [x] Clean out unprioritized inbox **✅2024-04-09 we have removed most stuff or migrated to PRIORITIZED**
- [x] Get a prioritized list of ideas **✅2024-04-09 see PRIORITIZED in https://github.com/datopian/datahub-next/issues/246**
- [ ] Get an overall sense of direction
- [ ] Identify what we shape - review prioritized ideas and select for shaping and/or look at what we have already shaped
- [x] Identify what we ship
```

```[tasklist]
### Misc
- [x] Update objectives based on what happened in https://github.com/datopian/datahub-next/issues/276 **✅2024-05-03 some time back in April**
```

# 2024-04-08 Datahub Cloud where are we going

Present: Daniela, Yoana, Rufus, Ola

## Agenda

- [x] Check in
- [x] Context
  - [x] We have this epic issue https://github.com/datopian/datahub-next/issues/276 **✅2024-04-08 did not review as up to date** 
    - [x] We have the datahub-next backlog https://github.com/datopian/datahub-next/issues **✅2024-04-08 see https://github.com/orgs/datopian/projects/20/views/20. Moved some stuff into inbox. Deduplicated issue about dev docs**
  - [x] Project kanban last iteration: https://github.com/orgs/datopian/projects/20/views/8 **✅2024-04-09 Rufus/Ola**
  - [x] We have this inbox of bugs and things to fix https://github.com/datopian/datahub-next/issues/246 **✅ Ola**
  - [x] We have the products backlog https://github.com/datopian/product/issues **✅2024-04-08 Yoana**
  - [x] We have the list of datahub issues **✅2024-04-08 Daniela** https://github.com/datopian/datahub/issues **✅ Ola (only copied over stuff related to DataHub Cloud)**
  - [x] We have some feedback from onboardings  https://github.com/datopian/product/blob/main/notes/feedback-from-dh-cloud-onboarding.md **✅2024-04-08 Daniela**
  - [x] We have some feedback from the hackathon https://docs.google.com/document/d/1Gtrd9zUDfp-IwL2CqXd3aoFjPb1ZenH7lkQvw6rWlv8/edit **✅2024-04-08 Rufus**
- [x] What is the desired outcome of this meeting: Consolidate everything 
  - [x] Decide which of these will be our one and only source of truth **✅2024-04-09 resolved in new workflow https://github.com/datopian/product/blob/main/README.md#workflow**
  - [x] Update it to include everything we have in our backlog **✅2024-04-09 we will update backlog**
  - [x] Prioritize **🚧2024-04-09 in progress!**

Question from Rufus:

- do you want clarity *today* or are we seeking to change process (in general) going forward **✅2024-04-08 seeking clarity *today***

**Comment by rufuspollock** [comment]
FIXED. This happened (to extent it happened) and resulted in #330
