### ISSUE TITLE
[epic] DataHub Cloud v1.2 (~6th May 2024)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#330]
> [!note]
>
> ### 🚩 Shipping 🚢 *and* shaping 📐 in backlog atm!! 
>
> Why? Because we still need to do some shaping during the ship cycle atm. Soon we will have shaped before ship cycle!

```[tasklist]
### Backlog
- [ ] https://github.com/datopian/datahub-next/issues/331
- [ ] https://github.com/datopian/datahub-next/issues/336
- [ ] https://github.com/datopian/datahub-next/issues/333
- [ ] https://github.com/datopian/datahub-next/issues/329
- [ ] https://github.com/datopian/datahub-next/issues/275
- [ ] https://github.com/datopian/datahub-next/issues/328
- [ ] https://github.com/datopian/datahub-next/issues/259
- [ ] https://github.com/datopian/product/issues/233
- [ ] https://github.com/datopian/datahub-next/issues/347
- [ ] https://github.com/datopian/datahub-next/issues/355
- [ ] https://github.com/datopian/product/issues/229
- [ ] https://github.com/datopian/datahub/issues/1099
- [ ] https://github.com/datopian/datahub-next/issues/351
- [ ] https://github.com/datopian/datahub-next/issues/133
- [ ] https://github.com/datopian/datahub-next/issues/356
- [ ] https://github.com/datopian/datahub-next/issues/374
- [ ] https://github.com/datopian/datahub-next/issues/307
- [ ] https://github.com/datopian/datahub-next/issues/277
- [ ] https://github.com/datopian/datahub-next/issues/350
- [ ] https://github.com/datopian/datahub-next/issues/349
- [ ] https://github.com/datopian/datahub-next/issues/372
```

**Comment by rufuspollock** [comment]
FIXED. This is now over. Note that we did not have objectives and KRs for April - we never really finished our planning!
