### ISSUE TITLE
Deploy v0.1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#4]
Deploy this nextjs. Static pages and some SSR.

## Acceptance

- [x] Deploy to cloudflare and switch next.datahub.io to this **2023-02-28 :heavy_check_mark: Done. See the project on CF: https://dash.cloudflare.com/83025b28472d6aa2bf5ae59f3724aa78/pages/view/datahub-next, and deployments: https://datahub-next.pages.dev/ and https://next.datahub.io/ . ~Will double check after some time to ensure the domain is working (currently getting an error, CF is under maintenance according to https://www.cloudflarestatus.com/).~ Working.** 
- [x] Decide on cloudflare vs vercel **✅2023-03-10 still rendering on cloudflare atm whilst static only. have a ssr working on vercel**
- [ ] If cloudflare ... get it working on cloudflare with server side routes - https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/ **✅2023-03-10 ❌ did not succeed with edge runtime so unless we use workers we leave for now. could try functions**

## Tasks

- [ ] Research cloudflare approach ...
  - [x] if we use cloudflare (pages) how do we have SSR? **✅2023-02-23 Ans: use edge runtime. https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/ (but a bit more complex).**
  - [x] try this out quickly to validate **✅2023-03-10 see extensive notes in #27 and soon in datahub.io/notes/nextjs-edge-learnings**
- [x] Tryout vercel **✅2023-03-10 - see below. it works modulo a weird symlink.**
- [x] Recommendation **✅2023-03-10 use vercel if we need SSR for now**

### Deploy to Cloudflare

**Deploy to Cloudflare with edge functions was unsuccessful**.

There are two supported runtimes for Next.js: `node` and `(experimental) edge`[^1]. 

In order to enable SSR support and API folder support on our deployment on Cloudflare, we have to change the Next.js runtime from `node` (default) to `experimental-edge`[^2], so that Cloudflare can deploy workers for those[^3] (CF workers use V8 and do not support Node.js).

Next.js edge functions have an important restriction: they do not support the native Node.js API[^4], hence not supporting other packages that rely on the native API, and the same also applies to CF Workers. To use edge functions, we'd have to restrict our usage of APIs to the ones that are supported, the list of supported APIs can be found in https://nextjs.org/docs/api-reference/edge-runtime .

In our "MDX pipeline", we are using many dependencies that depend on Node.js native API to work e.g: 

- `fs` dependent: mdx-mermaid, remark-wiki-link all, etc

I couldn't find a workaround for this issue. As mentioned in the next.js docs[^1]:

> Next.js' default runtime configuration is good for most use cases, but there are still many reasons to change to one runtime over the other one.
For example, for API routes that rely on native Node.js APIs, they need to run with the Node.js Runtime. However, if an API only uses something like cookie-based authentication, using Middleware and the Edge Runtime will be a better choice due to its lower latency as well as better scalability.

[^1]: https://nextjs.org/docs/advanced-features/react-18/switchable-runtime#runtime-differences

[^2]: https://vercel.com/docs/concepts/functions/edge-functions

[^3]: > The @cloudflare/next-on-pages CLI transforms the Edge Runtime components of your project into a _worker.js file which is deployed with Pages Functions - https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/

[^4]: > Native Node.js APIs are not supported. For example, you can't read or write to the filesystem
node_modules can be used, as long as they implement ES Modules and do not use native Node.js APIs - https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

**Comment by rufuspollock** [comment]
@demenech can you take care of the first acceptance criteria: setting up cloudflare build and then switching over of next.datahub.io to it.

**Comment by demenech** [comment]
Will do asap.

CC: @rufuspollock @olayway

**Comment by olayway** [comment]
@rufuspollock, @demenech so after googling around quite a bit I haven't really found a clear answer of which provider - cloudflare or vercel - is better. The only thing I think may be worth taking into account is the pricing model, i.e. on cloudflare bandwidth is unlimited for $25 plan, whereas on vercel it's 1TB/month for $20 plan. + I know @rufuspollock you're more inclined to cloudflare, so maybe let's just try it out for now. It seems Next.js SSR with edge functions is supported for over half a year already, so I'm guessing this has already been battle tested.

**Comment by rufuspollock** [comment]
@olayway ok. what are the criteria you have (e.g. question tree) e.g.

- what are the criteria
- how does each option evaluate against those criteria

**Comment by demenech** [comment]
@rufuspollock @olayway deployment to Cloudflare was unsuccessful. Please take see the notes I added to the ticket description. If ou have any ideas please let me know.

**Comment by rufuspollock** [comment]
> @rufuspollock @olayway deployment to Cloudflare was unsuccessful. Please take see the notes I added to the ticket description. If you have any ideas please let me know.

My immediate question is why those plugins have a dependency on `fs` and if we can eliminate it (that would be good anyway).

At the same time, we may just want to deploy on vercel for now (?)

**Comment by demenech** [comment]
@rufuspollock I will investigate. Deploying to Vercel should take just a few minutes.

**Comment by demenech** [comment]
## Update 2023-03-09

New branch created for the Vercel deployment: `with-SSR` (https://github.com/datopian/datahub-next/tree/with-SSR). 

Project: https://vercel.com/datopian1/datahub-next

### Issues

The following error was happening when trying to deploy the project to Vercel using the Next.js framework template:

```
Traced Next.js server files in: 1.178s
Created all serverless functions in: 3.571s
Collected static files (public/, static/, .next/static): 27.684ms
Error: ENOENT: no such file or directory, mkdir '/vercel/output/static/assets'
BUILD_FAILED: ENOENT: no such file or directory, mkdir '/vercel/output/static/assets'
```

The same error was also happening locally when trying to build the project with `vercel build` (https://github.com/vercel/vercel).

After some investigation, I noticed that in the Flowershow repo there are some symbolic link creations (see https://github.com/flowershow/flowershow/blob/main/scripts/symlink-site.js#L9) and also that in this project `public/assets` is a symbolic link pointing to `../content/assets`. 

The build command was falling because it was copying the symbolic link from `public/assets` to  `.vercel/outputs/static/assets`, therefore breaking the symbolic link.

```sh
$:~/Projetos/datahub-next/.vercel/output/static$ file assets 
assets: broken symbolic link to ../content/assets
```

#### Fix

To fix this, I had to unlink `public/assets` and `public/Excalidraw`, move `content/Excalidraw` and `content/assets` to the public folder, and then recreate the symlinks:

```bash
~/Projetos/datahub-next$ unlink public/Excalidraw
~/Projetos/datahub-next$ unlink public/assets
~/Projetos/datahub-next$ git mv content/assets public/assets
~/Projetos/datahub-next$ git mv content/Excalidraw/ public/Excalidraw
~/Projetos/datahub-next$ ln -s ../public/assets/ ./content/assets
~/Projetos/datahub-next$ ln -s ../public/Excalidraw/ ./content/Excalidraw
```

Commit: https://github.com/datopian/datahub-next/commit/988024e77afef877f51efe58037f04a9254299bb

### Results

After pushing this the deployment was finally successful. See: https://datahub-next.vercel.app/

@rufuspollock should I cherrypick the commit into `main`?

**Comment by rufuspollock** [comment]
@demenech /cc @olayway this is kind of weird as that kind of setup works fine (obviously) on cloudflare and on netlify and reversing the symlinking is kind of ugly (you want the actual stuff in the content folder). I'm guessing though this approach still works on cloudflare at least so whilst hacky it works 🙂

Medium term: the best solution here would be that assets were copied to "right" location as part of the build process.

**Comment by demenech** [comment]
@rufuspollock yes, should also work on other deployments. The Vercel CLI build seems to do some things in a different way, when I build with `next build` locally it works without reversing the symlinks it works as well.

**Comment by rufuspollock** [comment]
FIXED. this is working now.

Static rendering (cloudflare): https://datahub-next.pages.dev/tools/view
https://datahub-next.vercel.app/tools/view

Static rendering (vercel): https://datahub-next.vercel.app/tools/view

SSR (vercel): https://datahub-next-1lkuznexd-datopian1.vercel.app/tools/view?url=https://raw.githubusercontent.com/datopian/datahub-next/27-rendering-pipeline/__tests__/e2e/fixtures/markdown.md
