### ISSUE TITLE
Research existing data table / data grid libraries

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#41]
Data tables (aka data grids) are central to our dataset showcase and almost any kind of data presentation.

We want to research and summarize the existing JS libraries for presenting data so that we can choose the best one **plus** to have a nice bloggable summary to share with others (this is nice exercise in publishing product comparisons using data-literate model)

For some inspiration see https://github.com/datopian/line-charts

## Acceptance

Overall

* [ ] A list showing the pros and cons of different data table libraries published as post on datahub.io/blog (or if better as a separate mini site e.g. table-libraries.datahub.io ...)
* [ ] A list of key data table features
* [ ] Recommendations

Bonus

- [ ] Content/code lives in a public "dataset-like" repo where others can update it over time (an experiment in community driven product evaluation) - like we did with line charts https://datopian.github.io/line-charts/ / https://github.com/datopian/line-charts

Detailed

* [ ] List of JS data table/grid libraries with basic info e.g.
  * [ ] url / github url
  * [ ] name
  * [ ] stars
  * [ ] last updated
  * [ ] brief description
* [ ] Quick pass evaluation notes (internal) leading to a shortlisting of 2-4 that we dig into depth
* [ ] Working demos for each one

## Tasks

- [ ] List libraries focused on "top" ones
- [ ] Identify key features
- [ ] Evaluate against those
- [ ] Recommendations
