### ISSUE TITLE
[epic] MarkdownDB

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#46]
Create a static ContentBase of our markdown files so that I can quickly access the metadata and content I want. Use this to replace contentlayer.dev.

See https://datahub.io/notes/markdowndb

## Job Stories

When generating rendered pages I want to get a list of all or some of the markdown files we have so that i can render them and create blog index etc

When generating an individual rendered page i want information about all the pages that reference it so that i can list all the backlinks

When creating a tag page I want to list all pages with that tag so that I can generate that page

## Acceptance

- [ ] #31 

## Inbox

- [ ] Links
  - [ ] normal markdown
    - [ ] `[...](...)`
    - [ ] `![...](...)`
  - [ ] `[[...]]` wiki link style including with title
  - [ ] `![[...]]` for images and other embeds
- [ ] In file tags e.g. `#xyz` in body of the page (not frontmatter)
- [ ] Extracting tasks (see obsidian dataview)
- [ ] Analyse and implement types
  - [ ] Infer entity type
- [ ] Generate getters from types (kinda like a wrapper for the Query)
- [ ] Refactor: improve our interfaces, do something similar to CachedMetadata and CachedFile
- [ ] Ensure we can reindex folder to the same DB 🔽 i don't mind just rebuilding from scratch for now. this should be very fast ...

### Rufus random notes

- how can we get type stuff like contentlayer has e.g. a given type in markdown frontmatter leads to use of X typescript type/interface
- check out astro-build - how do they do type stuff?

###  Notes on obsidian dataview API

https://github.com/blacksmithgu/obsidian-dataview/discussions/1811

### Where is contentlayer.dev API used

Results of `ag contentlayer/generated`

```
content/getters/docs.js
1:import { allDocs } from "contentlayer/generated";

content/getters/blogs.js
1:import { allBlogs } from "contentlayer/generated";

content/getters/collections.js
1:import { allCollections } from "contentlayer/generated";

scripts/search.mjs
2:import { allDocuments } from "../.contentlayer/generated/index.mjs";

lib/getAuthorsDetails.js
2:import { allPeople } from "contentlayer/generated";

pages/_all.jsx
2:import { allPages } from "contentlayer/generated";

pages/[[...slug]].jsx
2:import { allDocuments } from "contentlayer/generated";
```
