### ISSUE TITLE
Sprint w/c 13 March 2023

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#48]
## Sprint Goals

- [x] Replace contentlayer and have one pipeline #32 **✅2023-03-17**
- [x] /@{owner}/{dataset} "works" at least for the README #21 **✅2023-03-18**

Bonus

- [ ] MarkdownDB improvements and docs #46 
  - [ ] "Landing page" for MarkdownDB in notes
  - [x] Job stories for MarkdownDB **✅2023-03-17 see https://datahub.io/notes/markdowndb#job-stories**
  - [ ] Research dataview for how it indexes files #47 
- [ ] Custom block => React object e.g. sql query against some data #65

### Questions

- [ ] what's the overall vision for the future of Flowershow as a separate package

### Branches

```mermaid
graph LR

main[Main at rev X]
main --> ssr[SSR for Vercel]
main --> mainctd[main continued]
mainctd --> main3[main 3]
mainctd --> ssrctd
ssr --> ssrctd
```

- Static generation for content (local or remote): `pages/flowershow-next/[...slug].ts]`
  - uses the new pipeline
  - uses new markdowndb
  - even should be able to statically remote content
- SSR: `/tools/view?url=...`
  - For on-demand rendering of (remote) content

### Why we wanted it Flowershow Next

|  |  | Flowershow v1 | Flowershow Next | Flowershow Next + SSR (Edge or Vercel) |
| -------- | -------- | -------- |-------- |-------- |
| Static   | Local     | ✅ | ✅ | ✅ |
| Static   | Remote     | ❌ | ✅ | ✅ |
| Server   | Local/Remote  | ❌ | ❌ | ✅ |

**Comment by SusanBot85** [comment]
Great Issue – thank you

**Comment by rufuspollock** [comment]
FIXED. Achieved core goals.
