### ISSUE TITLE
[inbox] David + Rufus

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#49]
## Tasks

- [x] Start dumping notes into datahub.io/note/data-projects-database
  - [ ] over time we can start categorizing into areas
- [ ] Note dump: DAOs and data collectives and data maintenance

## Inbox

Potential Outputs

- [ ] A blog post about the history of this area for datahub.io and david's blog
- [ ] Here are a list of companies in the data project space
- [ ] Here's what i learned as an enterprise data engineer from a month deep dive into the open source data and open data ecosystem
- [ ] Idea: Large language models for automated schema inference
- [ ] Idea: wasm for doing stuff in the browser
- [ ] Bounties: e.g. dolt
- [ ] Learnings from data curation DAOs (dune, metrics Dao, ...)

### List of data companies

List of the companies in this kind of space (alive and dead)

- And by area they tried to work on
- Taxonomy of ideas
- Family tree would be kind of cool ...

This could be a mini repo ...

github.com/datasets/history-of-data-projects

README.md
companies.csv
...

**Comment by davidgasquez** [comment]
Started with `datahub.io/note/data-projects-database` on https://github.com/datopian/datahub-next/pull/52.

I'm also [playing with a bunch of "Data Package Managers" in a playground repository](https://github.com/davidgasquez/data-package-managers-playground). Aiming to make it easier for people (basically me :sweat_smile:) to evaluate all the different options.

**Comment by davidgasquez** [comment]
Hey @rufuspollock! Can we move the different actionable issues to their own issues? I think there are 3 potential post ideas we could explore from the issue body.

1. A blog post about the history of this area for datahub.io and david's blog that's also a dataset (`github.com/datasets/history-of-data-projects`).
2. The "Here's what I learned as an data engineer from a month deep dive into the open source data and the open data ecosystem". A "how could the future look like" section could mention LLMs to reduce coordination friction (data-GPT to automate schema, types and location inference. point it somewhere, get a `datapackage.json`), and the potential role of WASM and modern tooling to make "small data" larger. 
3. Incentives in the Open Data Ecosystem. Bounties, DAOs, data collectives, data maintenance work, ...

Sounds good? I can split things up and close this one if I have a :+1:!

**Comment by rufuspollock** [comment]
@davidgasquez this sounds great.

**Comment by davidgasquez** [comment]
Done! Closing this one. Let me know if there are any other lingering things we can take care off! 

- https://github.com/datopian/datahub-next/issues/57
- https://github.com/datopian/datahub-next/issues/58
- https://github.com/datopian/datahub-next/issues/59
