### ISSUE TITLE
v0.1: switch table component to tanstack table

### ISSUE THREAD

**Issue by demenech** [datopian/datahub-next#5]
**Epic:** https://github.com/datopian/datahub-next/issues/3

We want to use [TanStack Table](https://tanstack.com/table/v8) as our table component for drd

## Acceptance criteria
- [x] The table component now uses TanStack Table **2023-02-28 :heavy_check_mark: Table component is now using TanStack Table, see https://github.com/datopian/datahub-next/pull/6**

## Tasks
- [x] Install TanStack Table on the project **2023-02-27 :heavy_check_mark: PR: https://github.com/datopian/datahub-next/pull/6**
- [x] Update the Table component that came with data literate to use it **2023-02-27 :heavy_check_mark: PR: https://github.com/datopian/datahub-next/pull/6**

## Screenshots
![image](https://user-images.githubusercontent.com/16550934/221672262-12e1e1bb-7b18-466f-bea5-eafd8e0dd1cb.png)
![image](https://user-images.githubusercontent.com/16550934/221672286-f62c197a-f58c-4585-970a-d3c366c48dfb.png)

**Comment by demenech** [comment]
@olayway can you review [this PR](https://github.com/datopian/datahub-next/pull/6), please? 

@rufuspollock should I add more tasks to this ticket or should we close it and move on?

**Comment by rufuspollock** [comment]
@demenech i think we can close for now and open new issues for follow up. I'll let you update acceptance and close. (note i changed title to be a bit more descriptive too)

**Comment by demenech** [comment]
FIXED. See commit https://github.com/datopian/datahub-next/commit/d346e7e9b6f8c432b7d0f2f6c265d3c68c4638b2 . Currently not deployed.
