### ISSUE TITLE
[drd] Custom SQL block for sql queries against data

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#65]
Custom block => React object e.g. sql query against some data

```sql
select * from ...
```

Results in a table on the page.

## Acceptance

- [ ] it works as per the above spec with csv files that are cors readable

## Tasks

- [ ] Custom remark plugin to extract the block and pass the info to internal system
- [ ] Data loader: Run the query and get a result set
- [ ] React component to render: turns the results into a table

### Questions

- [ ] What do we use for SQL in memory "database"?
 - [ ] duckdb
 - [ ] alasql
- [ ] What data sources do we support? e.g. csv, parquet, sqlite?
- [ ] How do we specific location of source data / database?
