### ISSUE TITLE
Showcase v0.2: display non-inline data (for remote content and data)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#69]
Rendering with data local to the project so we can show diagrams, tables etc with non-inline data

i.e. I have the following

```bash
README.md
data.csv
```

And README.md has something like the following and it renders a table:

```md

<DataTable src="data.csv" />
```

| Column 1 | Column 2 | Column 3 |
| -------- | -------- | -------- |
| Text     | Text     | Text     |

## Acceptance

- [x] A DataTable with relative CSV file path renders **FIXED. See https://datahub-next.vercel.app/@datahubio/test-data-repo-1/.** 
- [x] A Chart with relative CSV file path renders **FIXED. See https://datahub-next.vercel.app/@datahubio/test-data-repo-1/.** 

Bonus

- [x] Markdown files other than README.md get rendered e.g. `abc.md` in repo is at `abc` and `xyz/abc.md` at `xyz/abc` (note it is not necessary to rewrite README.md in subdirectories to be index path though that is nice) **FIXED. See https://datahub-next.vercel.app/@datahubio/test-data-repo-1/info.** 
- [ ] Blog post or note about this feature with a video
  - [ ] Demo site at demo.datahub.io?

## Tasks

- [x] Research approach
- [x] Update demo repo **:white_check_mark: 2023-03-22 added data.csv, see commit https://github.com/datahubio/test-data-repo-1/commit/138f628b40e9f6add81f653e24aeda0e55c91b59**
  - [x] and test (if possible)
- [x] Requests for `/@owner/project/{path}`
  - [x] If `{path} = ''` then render README.md
  - [x] If `{path}` has an extension is anything itself then proxy
    - [x] BONUS: it streams the read and the response
  - [x] BONUS: If `{path}` has no extension look up `{path.md}` and render through our pipeline

## Notes

How do we do this?

- [x] HACK inline the csv data server side into the CSV! Then no remote loading! **✅2023-03-20 ❌ This a bad idea b/c could be very slow, puts data processing burden on server rather than client, no way to load only some of the data etc.**
- [x] If not, we need to solve CORS problem. How do we do this?
    - [x] raw github? **✅2023-03-20 ❌ no b/c does not support cors**
    - [x] proxy? e.g. file `xxx` in source repo proxied to `/@owner/project/xxx` **✅2023-03-20 👍 **
      - [x] May need to check on link rewriting to make sure this works but should work ok w/o rewriting ...
    - [x] store the content into datahub's own storage and rewrite links **✅2023-03-20 FUTURE**

**Comment by demenech** [comment]
# Updates 2023-03-22

## Changes

- It's now possible to render the README.md of subpaths of a repo e.g https://github.com/datahubio/test-data-repo-1/tree/main/data -> `/@datahubio/test-data-repo-1/data`
- Now if a path ends with an extension, proxy the content of the file
- [WIP] relative links, like data.csv, resolve correctly on DRD pages
- Implemented a test for the rendering of a subpath's README.md

## Notes

### Handling pages and API requests on the same route based on whether the path has an extension or not

Used a rewrite rule to make it possible to render READMEs on `/path` and proxied content of a file on `/path.extension`.

```typescript
{
  source: "/@:org/:project/:file(\.\+\\\.\.\+\$)",
  destination: "/api/proxy?url=https://raw.githubusercontent.com/:org/:project/main/:file",
},
{
  source: "/@:org/:project*",
  destination: "/@org/:org/:project*",
},
```

Before that I tried:
- Using getServerSideProps
  - Won't work because we can only return templates from pages
-  Middleware
  - Could be interesting if our requirements become more complex, but I decided not to use it because the rewrite is simpler

### Handling URLs relative to the current path

The issue with relative links like `data.csv` on pages like `/@datahubio/test-data-repo-1` is that it will point to `/@datahubio/data.csv` instead of `/@datahubio/test-data-repo-1/data.csv

One way to fix this is setting the Next.js trailing slash setting (https://nextjs.org/docs/api-reference/next.config.js/trailing-slash) to `true`, so that `/@datahubio/test-data-repo-1` becomes `/@datahubio/test-data-repo-1/` and then `data.csv` points to `/@datahubio/test-data-repo-1/data.csv`. This works perfectly for this page (tested on https://github.com/datahubio/test-data-repo-1/tree/main/data), but on the other hand, it breaks other links across the website.

Still investigating a way to make it work without the trailing slash. Of course, we could fix this at the request level for the Table component, but the Vega components still depend on the trailing slash or another solution.

___

Draft PR: https://github.com/datopian/datahub-next/pull/74

**Comment by rufuspollock** [comment]
> One way to fix this is setting the Next.js trailing slash setting ([nextjs.org/docs/api-reference/next.config.js/trailing-slash](https://nextjs.org/docs/api-reference/next.config.js/trailing-slash)) to true, so that /@datahubio/test-data-repo-1 becomes /@datahubio/test-data-repo-1/ and then data.csv points to /@datahubio/test-data-repo-1/data.csv. This works perfectly for this page (tested on [datahubio/test-data-repo-1@main/data](https://github.com/datahubio/test-data-repo-1/tree/main/data?rgh-link-date=2023-03-22T22%3A05%3A57Z)), but on the other hand, it breaks other links across the website.

I like trailing slash in general. Where else does this break stuff? In the content folder? If we can we could switch to this.

Also i imagine this breakage only happens with the README.md which we have set as index page ... For example, if you have a `abc.md` with a reference to `data.csv` it probably works because (IIRC) a link to `data.csv` from `/@owner/repo/abc` will go to `/@owner/repo/data.csv` which is correct. So this is perhaps and artefact of our special treatment of README ...

**Comment by demenech** [comment]
## Updates 2023-03-23

- Updated demo repo, see https://github.com/datahubio/test-data-repo-1
- PR: render other md files at the root of the project and fix tests based on the new test repo: https://github.com/datopian/datahub-next/pull/77

CC: @rufuspollock

**Comment by demenech** [comment]
CLOSED. See PR https://github.com/datopian/datahub-next/pull/74 and examples https://datahub-next.vercel.app/@datahubio/test-data-repo-1/ and https://datahub-next.vercel.app/@datahubio/test-data-repo-1/info

**Comment by demenech** [comment]
## Issues with the current relative link implementation:

The trailing slash is causing some issues:

- Relative URLs won't work on pages other than READMEs (on READMEs the slug is empty)
- Trailing slash breaks the wiki links tests

**Comment by rufuspollock** [comment]
@demenech yes i thought we would cause issues on other pages ... Right now priority is the project showcase so we can ignore other pages (as long we aren't breaking content folder stuff e.g. are we breaking stuff in docs/dms etc).
