### ISSUE TITLE
Showcase for Frictionless (datapackage.json) Projects

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#76]
Showcase Frictionless datasets (on github) on DataHub Next.

A Frictionless dataset: is a dataset (has data files!) and has `datapackage.json` in its root folder.

Lots of examples at github.com/datasets

We want a dispaly similar to what we already have e.g. datahub.io/core/finance-vix which is a showcase of github.com/datasets/finance-vix

![image](https://user-images.githubusercontent.com/180658/227258150-f15be68f-bec1-469e-837f-ca535965a164.png)

## Acceptance

- [x] github.com/datasets/finance-vix shows up at `@datasets/finance-vix` **✅ 2023-03-24 Done. See PR below and preview: https://datahub-next-git-feature-frictionless-project-datopian1.vercel.app/@datasets/finance-vix** 
- [x] decent showcase **✅ 2023-03-24 Done. See preview: https://datahub-next-git-feature-frictionless-project-datopian1.vercel.app/@datasets/finance-vix** 
- [x] 🏆 other sub-pages still work e.g. `@datasets/finance-vix/abc` **✅ 2023-03-24 This is working. See example: README https://datahub-next-git-feature-frictionless-project-datopian1.vercel.app/@datahubio/test-data-repo-1 and file https://datahub-next-git-feature-frictionless-project-datopian1.vercel.app/@datahubio/test-data-repo-1/secondary**

## Tasks

- [x] Create a lib/types.tsx and create a Project object (see below)
- [x] Create the loader side: (for index page only): refactor https://github.com/datopian/datahub-next/blob/with-SSR/lib/project.ts
  - [x] Return Project object from `getProject` (no `getProjectReadme` anymore)
  - [x] Load datapackage.json (if exists) and sets metadata attribute with this object
  - [ ] LATER ~~Loads a README and extracts frontmatter into metadata~~ (Aside: this can reuse markdown db loader pipeline stuff one day!)
- [x] Refactor `[[slug]]` in https://github.com/datopian/datahub-next/tree/with-SSR/pages/%40org/%5Borg%5D/%5Bproject%5D to distinguish index page and other pages as index page is project page
- [x] Render showcase page differently if there is `metadata.resources` (i.e. we had a `datapackage.json`)
  - [x] Create frictionless-showcase layout (ultra simple)

### Views

- [x] Do a quick assessment of how many core datasets have views b/c if few we could just write this to use our new data rich approach **✅ 2023-03-24 See notes below. There are only 5 charts.**
  - [ ] at very least switch to vega or stuff like that

Implementation

- [x] Create a layout
  - [x] Design layout - let's follow existing datahub

## Notes

Most HACKy approach right now:

- Hard code that we know all stuff at `@datasets` are frictionless
- Explicitly load datapackage.json, set a special layout
- Render with that layout

### Showcase Design

![image](https://user-images.githubusercontent.com/180658/227258277-e927763a-173d-4d62-86c3-2d9976616a2f.png)

### Project Object

```
interface Project {
  // id:
  name: string # repo name
  owner: string # github owner
  // title: string
  github_repo: string[url]
  readme: string
  metadata: object
}

interface MarkdownFile {
  
}
```
### Questions

- [x] what does a Frictionless dataset look like? **✅ a `datapackage.json, README.md` plus some data files usually csvs**
  - [x] What examples? **✅ See e.g. https://github.com/datasets/finance-vix or https://github.com/datasets/oil-prices https://github.com/datasets/emojis**
- [x] What should result look like? **✅2023-03-23 somewhat similar to old version but flexible. Key things are:
  - [ ] title
  - [ ] elegant
  - [ ] readme
  - [ ] visualization
  - [ ] data files listed
  - [ ] What is not needed?
    - No need to support for zip versions or alternate formats
    - No need for all the instructions stuff for now
- [x] What about views? **✅2023-03-23 we will move them into the README by hand for now**
- [x] Is it time we create "projects"? **✅2023-03-23 Yes**

___

## Notes

- How many core datasets have views?
  - Question: if we rewrite the README, aren't we breaking https://datahub.io/search since the README section will then have mdx components syntax?
  - Datasets
    - https://datahub.io/core/country-codes - 1 table
    - https://datahub.io/core/country-list - 1 table
    - https://datahub.io/core/world-cities - 2 tables, 1 line chart
    - https://datahub.io/core/bond-yields-us-10y - 1 table, 1 chart
    - https://datahub.io/core/language-codes - 4 tables
    - https://datahub.io/core/oil-prices - 8 tables, 1 (broken) chart
    - https://datahub.io/core/airport-codes - 1 table
    - https://datahub.io/core/natural-gas - 2 tables, 1 chart
    - https://datahub.io/core/finance-vix - 1 table, 1 chart  
  - 5 charts total

## PRs

https://github.com/datopian/datahub-next/pull/79

**Comment by demenech** [comment]
WIP: https://github.com/datopian/datahub-next/pull/79

**Comment by demenech** [comment]
## Questions 2023-03-24

- Is this layout good enough? ![ss-2023-03-24-16:16:45](https://user-images.githubusercontent.com/16550934/227619666-7fdbc493-2113-4120-b8a7-21c4694f719c.png)
- Should I still hardcode the _branch name_ for @datasets repos?

**Comment by rufuspollock** [comment]
> Is this layout good enough?

Yes, for now. We can rapidly iterate that. Be nice to see some charts etc - and we can work on that.

> Should I still hardcode the branch name for https://github.com/datasets?type=source repos?

I think we are just defaulting to main - we can through and change the repos to be branch main.

**Comment by rufuspollock** [comment]
FIXED. Improved showcase and view stuff can be in follow ups.
