### ISSUE TITLE
v0.1 Tests (unit and e2e)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#8]
Setup basic e2e and unit tests.

Probably use playwright and jest.

## Acceptance

- [x] Have a unit test for something in lib (must be something!)
- [x] Have e2e test for our new API **works but only for tests without JSX components, see notes below**

## Tasks

- [x] configure E2E tests with playwright
  - [x] add basic E2E tests **03/01/2023 done, 1) goes to home page and tests the page title; 2) goes to home page and navigates to /blog page**
  - [x] make sure tests pass locally **03/01/2023 done**
  - [x] setup CI workflow **03/01/2023 e2e workflow created, tests pass in CI**
- [x] configure unit tests with jest **works but only for tests without JSX components, see notes below**
  - [x] add basic unit test of our `markdown.js` lib 
  - [x] make sure tests pass locally
  - [x] setup CI workflow

## Notes
⚠️ Unit tests with JSX component will fail with the following error atm:

```sh
 FAIL  __tests__/unit/index.test.jsx
  ● Test suite failed to run

    SyntaxError: Unexpected token '<'

      at Runtime.loadEsmModule (node_modules/jest-runtime/build/index.js:509:20)

Test Suites: 1 failed, 1 total
```

This is probably due to incorrect jest config and we'll have to make it work once we start testing our components.
Follow up issue created here: #24

**Comment by rufuspollock** [comment]
@olayway can you close this formally - e.g. update acceptance and probably just copy and paste your note from the PR here.

Also can you add your note about the anticipated issue with react testing.

**Comment by olayway** [comment]
@rufuspollock  There already was a note added in the description about this problem. But I've created a separate issue for it as well so that we don't forget. Closing this as this part is done.
