### ISSUE TITLE
[showcase] Views i.e. tables and charts for Frictionless projects

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#84]
"Views" i.e. tables and charts on Frictionless Datasets (follow up to #76)

## Acceptance

- [x] We have https://datahub.io/@datasets/finance-vix with a chart and a data table **✅ 2023-03-29 Working. See https://datahub-next-git-feature-fullwidth-components-datopian1.vercel.app/@datasets/finance-vix**
- [x] We have https://datahub.io/@datasets/oil-prices **✅ 2023-03-29 Working, had to fix the resourceName on the view. See https://datahub-next-git-feature-fullwidth-components-datopian1.vercel.app/@datasets/oil-prices**
- [x] Comparison with previous versions **✅ 2023-03-29 See notes about _What is deficient compared to the old version?_ below**
- [x] #92 **✅2023-03-30 ❌ move to own issue as substantial task**

Visualizations improvements **✅ 2023-03-29 See examples on the new test repo: https://datahub-next-git-feature-fullwidth-components-datopian1.vercel.app/@datahubio/test-data-repo-2**

- [x] Black
- [x] Fine line (not so thick)
- [x] Hover behaviour
- [x] Export as png / svg

Other improvements **✅ 2023-03-29 See examples on the new test repo: https://datahub-next-git-feature-fullwidth-components-datopian1.vercel.app/@datahubio/test-data-repo-2**

- [x] Full width for visualizations both inside README and outside
- [x] For tables (ditto)
- [x] (For images)

<img width="200" src="https://user-images.githubusercontent.com/16550934/228264399-e168f0fe-dc71-40fc-950a-ef32795b2ad2.png" />

## Tasks

- [x] Convert current view to LineChart (or vega-lite) as simply as possible
- [x] Make notes about the conversion process (maybe even make a small lib function - as we can reuse later) **✅  created a basic function that converts Simple specs to Vega specs,  see https://github.com/datopian/datahub-next/blob/with-SSR/lib/viewSpecConversion.ts and notes below**
- [x] Make notes about what is deficient compared to old version (picture in excalidraw?) **✅ 2023-03-29 See notes about _What is deficient compared to the old version?_ below**
- [ ] ...

### Example of a view on `finance-vix`

```json
"views": [
    {
      "name": "graph",
      "spec": {
        "group": "Date",
        "series": [
          "VIX Close"
        ],
        "type": "line"
      },
      "specType": "simple",
      "title": "VIX - CBOE Volatility Index"
    }
  ]
```

### Options

- Hand convert into README as a `<LineChart /> or <VegaLite .../>`
- In README you can have `<FrictionlessView viewid="" />` which renders the Frictionless View in that location
  - why? cleaner, allows a well-defined view that can be displayed e.g. for embedding elsewhere
- Something else e.g. markdown sections (triple backticks)

### Questions

- [x] Do we have a defined "views" object (like today) or just have stuff in the README? Is there a value of having this specified in the data package versus embedded in README? **✅2023-03-27 don't automate for now**
  - The "just in the README" is more "scratchpad" like and have it as a proper object is more Data Project like.
  - NB: even if an "object" big question of how it gets embedded. Current approach in DataHub v2 was a bit HACKy i.e. creata a data table (if tabular) for every resource/file in page. At top create something for display a view if view in views attribute of data package. (but unclear how to handle e.g. multiple views)
- [x] How do we handble table? **✅2023-03-27 using table object for now Later could do what we do in DataHub v2 and auto insert tables**
- [x] How many to fix? ~~There are only 5 charts to fix~~ **✅2023-03-27 Guessing around 42 charts to fix based on https://github.com/search?q=org%3Adatasets+%22views%22%3A&type=code**
- [x] What issues with putting in the READMEs? **It could look weird on the old dataset page on datahub.io because datahub.io also renders the readmes for the datasets, e.g https://datahub.io/core/finance-vix **✅2023-03-27 ❌ not a problem as old pages not updating**
  - [x] Is "views" is an extra field since I didn't find it on the spec: https://specs.frictionlessdata.io/data-package/#language **✅2023-03-27 see https://specs.frictionlessdata.io/views/**

### Notes about conversion

Since most datapackages in @datasets are using the "simple" spec for views, we have to convert this format to Vega in order to make it renderable.

This process is happening on `lib/viewSpecConversion.ts`. Example for `finance-vix`:

_Simple spec_

```javascript
    {
      "name": "graph",
      "spec": {
        "group": "Date",
        "series": [
          "VIX Close"
        ],
        "type": "line"
      },
      "specType": "simple",
      "title": "VIX - CBOE Volatility Index"
    }
```

_Vega spec_

```javascript
  let vegaLiteSpec = {
    $schema: "https://vega.github.io/schema/vega-lite/v5.json",
    mark: {
      type: view.spec.type, // "line"
      color: "black",
      strokeWidth: 1,
      tooltip: true,
    },
    title: view.title, // "VIX - CBOE Volatility Index"
    width: "container",
    height: 300,
    selection: {
      grid: {
        type: "interval",
        bind: "scales",
      },
    },
    encoding: {
      x: {
        field: x.name, // "Date"
        type: xType,  // Infered by using the resource schema: "date" => "temporal"
      },
      y: {
        field: y.name, // "VIX Close"
        type: yType, // Ingered by using the resource schema: "number" => "quantitative"
      },
    },
  };
```

### What is deficient compared to the old version?

- Missing metadata about the dataset, mainly:
  - Created
  - Updated
  - License
  - Source 
- Line chart tooltip in the old version is much easier to use
  - Example of a better tootip https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html
  - Not implemented in this issue because it might take some time to do it, I couldn't find clear examples that were not for multi series charts
- Chart and table embed functionality, we could have embeddings in a separate route
- Files list
  - Missing file metadata, such as size and description
  - Missing download link
- File preview:
  - No file download button
  - No embed functionality
  - No field information
- No integration section with code snippets

**Comment by demenech** [comment]
@rufuspollock I need some permission to change branch names on @datasets

**Comment by demenech** [comment]
## Updates 2023-03-27

### Draft PR:

https://github.com/datopian/datahub-next/pull/85

### Changes:

- Minor (as per the last review)
  - `DRD` component no longer handles layouts
    - We now wrap it inside an `MDLayout` component when necessary
    - Extracted the default layout to a `DefaultLayout` component
  - Titles are now being set using `NextSEO` instead of `<title>`
  - `Project.init()` renamed to `Project.initFromGithub()`
  - There are now two ways of instantiating a Project object: `getProjectFromGithub` and `getProject`
  - Implemented `Project.serialize()` so that we don't need `JSON.stringify` to pass props from `getServersideProps` to the pages that need the project obj
- The `DRD` component now supports a new component: `FrictionlessView`
  - `FrictionlessView` is a component factory that returns a data component capable of rendering charts based on a datapackage.json view obj  
  - It calls `lib/viewSpecConversion.ts` file methods to convert datapackage views to vega specs
    - Currently very limited, but it's capable of rendering the `finance-vix` chart
    - See the preview: https://datahub-next-git-feature-frictionless-showcase-views-datopian1.vercel.app/@datasets/finance-vix 
      - Scroll to the bottom of the page
      - Note that rn we are programmatically appending the chart using ```content += "<FrictionlessView viewId={0} />";```, we can later add this snippet to the README

**Comment by rufuspollock** [comment]
> @rufuspollock I don't have the necessary permissions to change branch names or approve PRs on @datasets, so to make changes I'll have to create PRs and assign you as the reviewer

Fixed - you should have invite.

**Comment by rufuspollock** [comment]
> ## Updates 2023-03-27

Great job.

> Note that rn we are programmatically appending the chart using content += "<FrictionlessView viewId={0} />";, we can later add this snippet to the README

I think we can move away from modifying README and just go straight to our option 2 which was having a proper "Frictionless Project" layout that imitates old DataHub and having the views at the top (and then README below) like on DataHub v2.

**Comment by rufuspollock** [comment]
Updated the acceptance with some more improvements we can do.

**Comment by demenech** [comment]
## Updates 2023-03-28

### Changes

- `FrictionlessView`
  - Zoom with mouse wheel 
  - Line charts are now black
  - Line thickness reduced
  - Show the tooltip on hover
  - Click on the three dots to export a chart to SVG or PNG
  - `<FrictionlessView viewId={0} fullWidth />` will render a full width chart (and it's responsive) ![ss-2023-03-28-17:58:34](https://user-images.githubusercontent.com/16550934/228365305-531d285d-ab0a-4f68-a860-e48b06c9ba36.png)
- Added data previews below the Data files section (basically just rendering tables)

### Notes

#### Vega Lite tooltip

The issue with the current tooltip is that it's often hard to find the exact point that triggers the information box on line charts. I suggest we implement a tooltip functionality like this one in the future: https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html

**Comment by rufuspollock** [comment]
> The issue with the current tooltip is that it's often hard to find the exact point that triggers the information box on line charts. I suggest we implement a tooltip functionality like this one in the future: [vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html](https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html)

Yes, can we do that?

**Comment by demenech** [comment]
@rufuspollock can we do this in the future? I took a look at some examples but I think it's going to take some time to figure this out

**Comment by rufuspollock** [comment]
FIXED. All done. See https://datahub-next-git-feature-fullwidth-components-datopian1.vercel.app/@datahubio/test-data-repo-2 and acceptance.
