### ISSUE TITLE
[tutorial]: Publishing data rich doc on DataHub (Next) v0.1

### ISSUE THREAD

**Issue by demenech** [datopian/datahub-next#89]
When new to the DataHub I want to know how to publish datasets, data stories and data rich documents on it so that I can take advantage of its awesome features.

💡 use datahub itself to publish the tutorial! (very dogfoody and meta)

## Acceptance

- [x] Tutorial for data rich documents (README + data) **✅ 2023-03-30  Done, see https://github.com/datahubio/tutorial and https://datahub-next.vercel.app/@datahubio/tutoria and https://demo.datahub.io/@datahubio/tutorial**
- [x] Blog post about this (or even tutorial itself - can we copy and paste ... hmm no, issues with data perhaps!) maybe more of the core text and some screenshots + video and a link to the tutorial **✅ 2023-04-01 Done, see https://drd-tutorial-blog.datahub-next.pages.dev/blog**
- [x] 🏆 these are live on DataHub itself (or demo) at e.g. `demo.datahub.io/@datahubio/tutorial` **✅2023-03-31 running at https://datahub-next.vercel.app/@datahubio/tutorial and https://demo.datahub.io/@datahubio/tutorial**

## Tasks

- [x] Create a first repo called `tutorial` **✅ 2023-03-30 Done. See https://github.com/datahubio/tutorial**
- [x] Create the simplest sketch possible (no images etc yet) **✅ 2023-03-39 Created a sketch, see https://github.com/datahubio/tutorial** 
- [x] Push it **✅ 2023-03-39 Done.**

### Outline: Simplest possible

- Create a github repo
- Push a README.md to it
- Go to the url!

Features to cover:

- Tables
- Graphs

### Outline Frictionless Dataset tutorial

- Crate a GitHub repo
- Push a datapackage.json with a view and a data file to it
- Push a README to it
- Go to the URL

### Bonus: beautiful example

- How do you get this result ... (i.e. have a nice demo with the features)
- Well you do this ...

**Comment by davidgasquez** [comment]
Very interested on this! Feel free to ping me whenever is more or less ready and I'd be happy to give it a run and provide feedback.

**Comment by rufuspollock** [comment]
> I found a weird issue that's happening on our LineCharts. Note that this is happening even without the PR mentioned above. The data object is correct:

This could be a bug in year / date parsing ie. interpreting `1850` as a float or something (i'm not sure). But my first effort would be to see if this reproduces if you explicitly parse that to date with the vega parse options or something similar.

**Comment by rufuspollock** [comment]
> First tutorial repo created, see [datahubio/tutorial](https://github.com/datahubio/tutorial) and [datahub-next.vercel.app/@datahubio/tutorial](https://datahub-next.vercel.app/@datahubio/tutorial)

The tutorial looks great. 👌

I think we turn this straight into a blog post by copying and pasting the README.md content into the blog folder here - maybe just with a tweak to say you can see the demo repo live at demo.datahub.io/@datahubio/tutorial

<details>
  <summary>you might ask: why duplicate the repo to blog!</summary>
  
That is something to think about for the future. For now, answer is:

- We want something on blog
- Blog can act as a static snapshot whilst the live tutorial repo can be updated
- Live tutorial was a test
- People can clone the tutorial repo
- DRY is overdone 😉
</details>

**Comment by demenech** [comment]
## Updates 2023-04-01

### Changes

- Managed to fix the _TOO_MANY_REDIRECTS_ issue I was having when assigning the `demo.datahub.io` domain on Cloudflare to Vercel by simply disabling the Cloudflare proxy. Working now: https://demo.datahub.io/@datahubio/tutorial
- Created a blog post about publishing data rich documents on DataHub with a demo video and a link to the live tutorial, see https://drd-tutorial-blog.datahub-next.pages.dev/blog

**Comment by davidgasquez** [comment]
Sharing a couple of small friction points I've encountered:

1. Creating an account on Datahub is not clear. Should I click _See the Demo_ or something else? Perhaps this is something that could be inside the tutorial itself to have an end to end description of the flow?
2. When exploring the source in GitHub, would be cool to have a way (badge, URL in description, ...) to point to the rendered version. E.g: https://github.com/datahubio/tutorial pointing to https://demo.datahub.io/@datahubio/tutorial.

**Comment by demenech** [comment]
hey @davidgasquez 

We are at a very early stage rn, so an account is not yet necessary to follow the tutorial, you can try to render any repo by changing the params in the URL. We are starting to work on actually indexing repos on #11.

About the link to the rendered version, that's a good idea. I'll add a link to the description, thank you!
