### ISSUE TITLE
Search Page v1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#9]
Search page for DataHub Next.

## Examples

Here's example from git-dms v1.

![](https://i.imgur.com/IdZc2OE.jpg)

Here's from datahub.io v2

![](https://i.imgur.com/mDTfFHm.jpg)

## Acceptance

- [ ] Search page e.g. at `/search-next` (b/c don't want to mess with current name) that has search
- [ ] Shows (data) projects that are indexed in typesense

## Tasks

- [ ] Design: Keep it super simple e.g. what we have in git dms v1 or in datahub.io/search
  - [ ] Future: Select the best search page layout. Eg, hdx or other ckan examples where we have faceted search. Sketch in figma
- [ ] Implement a new search page and connect to typesense API
