### ISSUE TITLE
Tutorial Publishing Frictionless datasets v0.1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#97]
**Follow up: https://github.com/datopian/datahub-next/issues/89**

_When new to the DataHub I want to know how to publish Frictionless datasets on it so that I can take advantage of its awesome features._

Same dogfooding approach as #89

## Acceptance

- [x] Tutorial live at `demo.datahub.io/@datahubio/tutorial-frictionless-dataset` **✅ 2023-04-03 See results at https://demo.datahub.io/@datahubio/tutorial-frictionless-project and repo https://github.com/datahubio/tutorial-frictionless-project**

## Tasks

- [x] Create the `datahubio/tutorial-frictionless-project` repo
- [x] Write the tutorial according to the notes below

### General guideline

- Main thing to cover is the novel stuff e.g. datapackage.json (which we assume people know about for now (can add reference to existing tutorails if necessary later) and `FrictionlessView` functionality
- Lead of article (add at end as needs content) from this in github [screnshot of repo] to this on DataHub ... [screenshot]
- Now let's walk through how we did that

### Outline

- Create a GitHub repo
- Push a datapackage.json with a view and a data file to it
- Push a README to it
- Go to the URL
