### ISSUE TITLE
Sign up for an Account (and logout + basic dashboard)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-next#99]
We want a way to sign up for an account.

Could use https://github.com/vercel/nextjs-subscription-payments - only changes would be

- No email signup - just github for now
- Let's keep the billing in but maybe comment out  or reduce to one plan atm e.g. "Supporter" (we haven't decided on plans yet but we will want billing)

## Job Stories

When I come to DataHub i want to sign up (with github) so that I have an account and can see my dashboard and take actions that require authentication

## Acceptance

- [x] Quick evaluation and recommendation (with reasons) of using supabase vs our own postgres + next-auth or similar 
   - The main advantage of Next-Auth was the fact that we already had worked with that to on previous project, but it turned out  that Supabase was pretty easy to setup, only 1/3 of the time spent on this feature was actually spent there the rest was making the tests work, and the good thing is that now we have a database that can be used in the future. 
- [x] Can signup (with github) (get fullname, email, avatar?) **✅ 2023-04-04 Working. See https://datahub-next-git-fork-luccasmmg-signin-datopian1.vercel.app/dashboard**
  - [ ] FUTURE: can selectively grant access to specific orgs!
- [x] Can signout **✅ 2023-04-04 Working. See https://datahub-next-git-fork-luccasmmg-signin-datopian1.vercel.app/dashboard**
- [x] Have a dashboard page (either at /dashboard or take over home page) with minimal info e.g. your full name, username, gravatar and date you signed up to datahub **✅ 2023-04-04 Working. See https://datahub-next-git-fork-luccasmmg-signin-datopian1.vercel.app/dashboard**

FUTURE?

- [ ] 🏆 ?? can delete my account

## Tasks

- [x] Create supabase account/project(Currently on my personal account)
- [x] Create github app(Currently on my personal account)
- [x] Add login page
- [x] Add dashboard page
- [x] Add logic to check if user is logged
- [x] Add user login dropdown
- [x] Added tests
- [x] Added information about env variables in README

## Pendings
As can be seen here in the Dashboard, the top bar doesnt behave very well with the TailwindUI layout, as per @demenech recomendation what i suggest is that in another PR we remove the `<Layout>` component from the _app.tsx file and add on a page per page basis
![Uploading image.png…]()

**Comment by luccasmmg** [comment]
@rufuspollock i already have pretty much everything related to login and password working, do you want me to
1. wrap everything by adding tests and docs and pick up stuff from other issues
2. add billing as well

**Comment by demenech** [comment]
FIXED. See commit https://github.com/datopian/datahub-next/commit/2440778e2d03fe881a74ce7dba35de3565fb7097.

Future:
- Update logo on the top left corner
- Move Layout one level down (so that it's applied to individual pages)
- Maybe tweak the colors
